spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/icons
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  paginacao:
    tamanho-pagina: 10

server:
  port: 8080

google:
  service-account:
    key-path: classpath:google-service-account.json
  drive:
    folder-id: 1axowLHi6vt3bhSJh23Xkim22t9zY0Gxg
